import React from "react";
import Head from "next/head";
import { NextSeo } from "next-seo";
import { AppConfig } from "@/utils/AppConfig";
type IMetaProps = {
    title: string;
    description: string;
    canonical?: string;
};
const Meta = (props: IMetaProps) => {
    return (
        <React.Fragment>
            <Head>
                <title>Delivery App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />

                {/* <link
                    href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css"
                    rel="stylesheet"
                    integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor"
                    crossOrigin="anonymous"
                /> */}
            </Head>
            <NextSeo
                title={props.title}
                description={props.description}
                canonical={props.canonical}
                openGraph={{
                    title: props.title,
                    description: props.description,
                    url: props.canonical,
                    locale: AppConfig.locale,
                    site_name: AppConfig.site_name,
                }}
            />
        </React.Fragment>
    );
};

export default Meta;
